"""add_partner_multitenancy_and_feedbacks

Revision ID: 515b59cf50f8
Revises: 497099c331ca
Create Date: 2025-11-24 11:15:27.496211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b59cf50f8'
down_revision: Union[str, None] = '497099c331ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Adiciona suporte a multi-tenancy (parceiros) e sistema de feedbacks.
    
    IMPORTANTE: Esta migration cria um parceiro padrão e vincula dados existentes a ele.
    """
    from sqlalchemy.dialects.postgresql import UUID
    import uuid
    from datetime import datetime
    
    # 1. Criar tabela de parceiros
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=True)
    
    # 2. Criar parceiro padrão para dados existentes
    default_partner_id = str(uuid.uuid4())
    op.execute(f"""
        INSERT INTO partners (id, name, is_active, created_at, updated_at)
        VALUES ('{default_partner_id}', 'Parceiro Padrão', true, '{datetime.utcnow()}', '{datetime.utcnow()}')
    """)
    
    # 3. Adicionar colunas partner_id (nullable inicialmente)
    op.add_column('clients', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.add_column('consultants', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('partner_id', sa.UUID(), nullable=True))
    
    # 4. Atualizar registros existentes com o parceiro padrão
    op.execute(f"UPDATE clients SET partner_id = '{default_partner_id}'")
    op.execute(f"UPDATE consultants SET partner_id = '{default_partner_id}'")
    # Nota: users.partner_id permanece NULL para admin global
    
    # 5. Alterar colunas para NOT NULL onde necessário
    op.alter_column('clients', 'partner_id', nullable=False)
    op.alter_column('consultants', 'partner_id', nullable=False)
    
    # 6. Criar foreign keys
    op.create_foreign_key('fk_clients_partner', 'clients', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key('fk_consultants_partner', 'consultants', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key('fk_users_partner', 'users', 'partners', ['partner_id'], ['id'])
    
    # 7. Atualizar ENUM UserRole
    # Converter temporariamente para VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50)")
    
    # Atualizar valores antigos para novos (case insensitive)
    op.execute("UPDATE users SET role = 'admin_global' WHERE LOWER(role) = 'admin'")
    op.execute("UPDATE users SET role = 'user_partner' WHERE LOWER(role) = 'leitura'")
    op.execute("UPDATE users SET role = 'admin_partner' WHERE LOWER(role) = 'gestor'")
    
    # Remover o ENUM antigo e criar o novo
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    op.execute("CREATE TYPE userrole AS ENUM ('admin_global', 'admin_partner', 'user_partner')")
    
    # Converter de volta para ENUM
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    
    # 8. Criar tabela de feedbacks
    op.create_table('consultant_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Remove o suporte a multi-tenancy e feedbacks.
    ATENÇÃO: Esta operação pode resultar em perda de dados!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Remover tabela de feedbacks
    op.drop_table('consultant_feedbacks')
    
    # 2. Reverter ENUM UserRole
    # Converter temporariamente para VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50)")
    
    # Reverter valores novos para antigos
    op.execute("UPDATE users SET role = 'admin' WHERE role = 'admin_global'")
    op.execute("UPDATE users SET role = 'leitura' WHERE role = 'user_partner'")
    op.execute("UPDATE users SET role = 'gestor' WHERE role = 'admin_partner'")
    
    # Remover o ENUM novo e recriar o antigo
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'gestor', 'leitura')")
    
    # Converter de volta para ENUM
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    
    # 3. Remover foreign keys
    op.drop_constraint('fk_users_partner', 'users', type_='foreignkey')
    op.drop_constraint('fk_consultants_partner', 'consultants', type_='foreignkey')
    op.drop_constraint('fk_clients_partner', 'clients', type_='foreignkey')
    
    # 4. Remover colunas partner_id
    op.drop_column('users', 'partner_id')
    op.drop_column('consultants', 'partner_id')
    op.drop_column('clients', 'partner_id')
    
    # 5. Remover tabela de parceiros
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###













