"""add_timesheets_invoice_fields_consultant_photo

Revision ID: a1b2c3d4e5f6
Revises: 515b59cf50f8
Create Date: 2025-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '515b59cf50f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Adiciona:
    - Campos de Nota Fiscal no modelo Installment
    - Campo de foto no modelo Consultant
    - Campo rating no modelo ConsultantFeedback
    - Tabela Timesheet para histórico de faturamentos
    - Remove campo feedback do Consultant (agora é calculado)
    """
    import uuid
    from datetime import datetime
    
    # 1. Adicionar campos de Nota Fiscal em installments
    op.add_column('installments', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('installments', sa.Column('billing_date', sa.DateTime(), nullable=True))
    op.add_column('installments', sa.Column('payment_term', sa.Integer(), nullable=True))
    op.add_column('installments', sa.Column('expected_payment_date', sa.DateTime(), nullable=True))
    op.add_column('installments', sa.Column('payment_date', sa.DateTime(), nullable=True))
    
    # 2. Adicionar campo de foto no Consultant
    op.add_column('consultants', sa.Column('photo_url', sa.String(length=500), nullable=True))
    
    # 3. Adicionar campo rating no ConsultantFeedback
    op.add_column('consultant_feedbacks', sa.Column('rating', sa.Integer(), nullable=True))
    
    # 4. Remover campo feedback do Consultant (agora é calculado como média)
    # NOTA: Os dados do feedback serão perdidos, mas podem ser recalculados a partir dos feedbacks
    # Se houver dados importantes, migre-os manualmente antes de executar esta migração
    op.drop_column('consultants', 'feedback')
    
    # 5. Criar tabela de timesheets
    op.create_table('timesheets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('contract_id', sa.UUID(), nullable=False),
        sa.Column('installment_id', sa.UUID(), nullable=True),
        sa.Column('timesheet_file_url', sa.String(length=500), nullable=True),
        sa.Column('hours_consumed', sa.Numeric(10, 2), nullable=True),
        sa.Column('approver_name', sa.String(length=255), nullable=True),
        sa.Column('approval_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
        sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_contract_id'), 'timesheets', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Remove as alterações feitas no upgrade.
    ATENÇÃO: Esta operação pode resultar em perda de dados!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Remover tabela de timesheets
    op.drop_index(op.f('ix_timesheets_contract_id'), table_name='timesheets')
    op.drop_table('timesheets')
    
    # 2. Adicionar campo feedback de volta no Consultant
    op.add_column('consultants', sa.Column('feedback', sa.Integer(), nullable=True, server_default='0'))
    
    # 3. Remover campo rating do ConsultantFeedback
    op.drop_column('consultant_feedbacks', 'rating')
    
    # 4. Remover campo photo_url do Consultant
    op.drop_column('consultants', 'photo_url')
    
    # 5. Remover campos de Nota Fiscal de installments
    op.drop_column('installments', 'payment_date')
    op.drop_column('installments', 'expected_payment_date')
    op.drop_column('installments', 'payment_term')
    op.drop_column('installments', 'billing_date')
    op.drop_column('installments', 'invoice_number')
    # ### end Alembic commands ###

