"""Add responsible_name and payment_method to contracts

Revision ID: 8867367fbb0b
Revises: dd14e6c201c2
Create Date: 2026-01-12 12:35:22.610864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8867367fbb0b'
down_revision: Union[str, None] = 'dd14e6c201c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('responsible_name', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'payment_method')
    op.drop_column('contracts', 'responsible_name')
    # ### end Alembic commands ###

















