"""Add timesheets model and relation to consultant

Revision ID: dd14e6c201c2
Revises: e5c8a93f973f
Create Date: 2026-01-07 17:01:58.655528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd14e6c201c2'
down_revision: Union[str, None] = 'e5c8a93f973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'is_strategic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('partners', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('partners', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('partners', 'is_strategic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###

















