"""Add partner status/strategic, client cnpj/razao, timesheet fields, fix UserRoleType

Revision ID: e5c8a93f973f
Revises: 310fa39cefb5
Create Date: 2026-01-07 13:53:15.295894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c8a93f973f'
down_revision: Union[str, None] = '310fa39cefb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cnpj', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('razao_social', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_clients_cnpj'), 'clients', ['cnpj'], unique=False)
    op.add_column('partners', sa.Column('is_strategic', sa.Boolean(), nullable=True))
    op.add_column('partners', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('timesheets', sa.Column('consultant_id', sa.UUID(), nullable=True))
    op.add_column('timesheets', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.add_column('timesheets', sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('timesheets', sa.Column('approver', sa.String(length=255), nullable=True))
    op.add_column('timesheets', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('timesheets', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_timesheets_contract_id'), table_name='timesheets')
    op.drop_constraint(op.f('timesheets_installment_id_fkey'), 'timesheets', type_='foreignkey')
    op.create_foreign_key(None, 'timesheets', 'consultants', ['consultant_id'], ['id'])
    op.drop_column('timesheets', 'created_at')
    op.drop_column('timesheets', 'timesheet_file_url')
    op.drop_column('timesheets', 'installment_id')
    op.drop_column('timesheets', 'approver_name')
    op.drop_column('timesheets', 'updated_at')
    op.drop_column('timesheets', 'hours_consumed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=backend.models.UserRoleType(length=50),
               type_=postgresql.ENUM('admin_global', 'admin_partner', 'user_partner', name='userrole'),
               existing_nullable=False)
    op.add_column('timesheets', sa.Column('hours_consumed', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('timesheets', sa.Column('approver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('installment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('timesheet_file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timesheets', type_='foreignkey')
    op.create_foreign_key(op.f('timesheets_installment_id_fkey'), 'timesheets', 'installments', ['installment_id'], ['id'])
    op.create_index(op.f('ix_timesheets_contract_id'), 'timesheets', ['contract_id'], unique=False)
    op.drop_column('timesheets', 'uploaded_at')
    op.drop_column('timesheets', 'approved')
    op.drop_column('timesheets', 'approver')
    op.drop_column('timesheets', 'hours')
    op.drop_column('timesheets', 'file_url')
    op.drop_column('timesheets', 'consultant_id')
    op.drop_column('partners', 'status')
    op.drop_column('partners', 'is_strategic')
    op.drop_index(op.f('ix_clients_cnpj'), table_name='clients')
    op.drop_column('clients', 'razao_social')
    op.drop_column('clients', 'cnpj')
    # ### end Alembic commands ###

















